name: Push translations
on:
  push:
    paths:
      - 'Locales/enUS.lua'
jobs:
  push:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Push Translations to CurseForge
        run: ./push-translations.sh
        env:
          CF_PROJECT_ID: "515611"
          CF_SOURCE: Locales/enUS.lua
