name: Package and release
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Push Translations to CurseForge
        run: ./push-translations.sh
        env:
          CF_PROJECT_ID: "515611"
          CF_SOURCE: Locales/enUS.lua

      - name: Package and release
        uses: BigWigsMods/packager@v2
